* Implementation details

** completion libraries used
- marginalia
- embark
- consult

** data structures used
Completion candidates are [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Properties.html][propertized strings]] with ='category= and ='multi-data= properties set.

The value of the string is the display text for the candidate, which is typically the name of the item. 

The ='category= property is a symbol that indicates the type of completion candidate, such as ='track=, ='artist=, ='album=, etc.

The ='multi-data= property is a hash table, implemented with the [[https://github.com/Wilfred/ht.el][=ht=]] library, 

** async vs. requests
Because consult is being used, async as well as sync versions of requests are used.  Consult abstracts away the need to implement functions that can asynchronously build lists of candidates and 'gather' them.  We defer this feature to consult. 

** mutex and cache

*** why it's needed
The spotify api provides a single convenient endpoint for searching all entity types (album, artist, track, etc...).  This endpoint is leveraged by this library (see below).

These entity types should be treated as different completion categories by emacs.

consult sources are associated with a single request (eg the search request), and consult sources can only have a single category, so in order to get multiple categories, we need to have multiple consult sources which issue the same (search) request.  To prevent wastefully issuing the same request multiple times, we cache the results of the request, and we use a mutex to prevent the race condition where multiple sources are trying to access the cache at the same time.

*** implementation detail

The library uses a mutex to ensure that only one thread can access the cache at a time. The cache is implemented as a hash table, which is created when the library is loaded.

** note on using a single endpoint
TODO improve this explanation
- prevents having to implement functions to support all possible combinations of entity traversal (eg artist -> tracks, artist -> albums) etc...
