;;; smoke-modules.el --- Load the time-management modules against the fixture -*- lexical-binding: t; -*-

;; Not an ERT suite: the module files under modules/org are loaded the
;; way the config loads them (use-package and general from the elpaca
;; builds, the config's own keyword stripped), then every ritual's
;; compute-and-draw is run over a COPY of testdata/todo -- the rituals
;; write tags, stamps and scores, and the fixture is generator output.
;; A failed assertion is a non-zero exit.  Run from the repository root:
;;
;;   emacs -Q --batch -l source/zettapkg/smoke-modules.el
;;
;; run-tests.sh runs it last.

;; Load the wave-1 modules the way the config would, against the fixture.
(let* ((root default-directory) (builds (expand-file-name "elpaca/builds" root)))
  (dolist (dir (directory-files builds t "\\`[^.]")) (when (file-directory-p dir) (add-to-list 'load-path dir))))
(setq user-emacs-directory default-directory)
(defvar smoke-dir (make-temp-file "zettapkg-smoke-" t)
  "A copy of the fixture: the rituals write tags, stamps and scores.")
(copy-directory (expand-file-name "testdata/todo") (expand-file-name "todo" smoke-dir) t t t)
(copy-file (expand-file-name "testdata/routine.org") (expand-file-name "routine.org" smoke-dir))
(setq zetta-org-routine-test-file (expand-file-name "routine.org" smoke-dir))
(require 'use-package)
(require 'general)
(defvar menu-org-map (make-sparse-keymap))
(defgroup zetta nil "stub" :group 'emacs)
(defvar zetta-org-todo-source 'test)
;; The kb root the modules derive their paths from (bootstrap-modules.el);
;; the real one, so the smoke test's view of the modules is the config's.
(defvar zetta-kb-dir "~/kb/")
(defun zetta-kb-file (relative) (expand-file-name relative zetta-kb-dir))
(defun zetta-org-toggle-todo-source (&optional _) nil)
(defvar brushup-styles nil)
(require 'org)
(require 'org-id)
(setq org-id-locations-file (expand-file-name "ids" smoke-dir) org-id-track-globally nil
      org-todo-keywords '((sequence "TODO(t!)" "NEXT(N!)" "PROG(p!)" "AGENT(a!)" "WAIT(w@/!)" "QUES(q@/!)" "HOLD(h@/!)" "IDEA(i!)" "|" "DONE(d!)" "NOPE(n@/!)"))
      org-log-into-drawer t)
;; The :brushup use-package keyword is config-local; drop it for the smoke test.
(defun zetta--strip-brushup (form)
  (let (out (skip nil))
    (dolist (x form) (cond (skip (setq skip nil)) ((eq x :brushup) (setq skip t)) (t (push x out))))
    (nreverse out)))
(defmacro use-package-nobrushup (&rest body) `(use-package ,@(zetta--strip-brushup body)))
(with-temp-buffer
  (insert-file-contents "modules/org/org-queue.el")
  (goto-char (point-min))
  (while (re-search-forward "^(use-package org-queue$" nil t) (replace-match "(use-package-nobrushup org-queue"))
  (eval-buffer))
(load-file "modules/org/org-routine.el")
(load-file "modules/org/org-daylog.el")
(setq org-agenda-files (directory-files (expand-file-name "todo" smoke-dir) t "^(todo).*\\.org$"))
(setq org-queue-history-file (expand-file-name "history.el" smoke-dir)
      org-queue-apply-log-file (expand-file-name "applies.el" smoke-dir)
      org-queue-inbox-file nil)
;; Loading the package triggers the derivation.
(require 'org-queue)
(message "buckets: %S" (mapcar #'car org-queue-buckets))
(message "capacity Mon: %S (derived from fixture table)" (alist-get 1 org-queue-capacity))
(cl-assert (alist-get 'work org-queue-buckets))
(cl-assert (= 570 (alist-get 1 org-queue-capacity)))
(let ((plan (org-queue-plan 20260912)))
  (message "plan: %s" (org-queue-core-summary plan))
  (org-queue-record-plan plan))
(let ((projects (org-queue-dormant-projects)))
  (message "projects: %S" (mapcar (lambda (p) (cons (plist-get (plist-get p :task) :title) (plist-get p :status))) projects))
  (cl-assert (eq 'dormant (plist-get (cl-find "Vendor evaluation" projects :key (lambda (p) (plist-get (plist-get p :task) :title)) :test #'string-prefix-p) :status)))
  (cl-assert (eq 'finished (plist-get (cl-find "Q2 retrospective" projects :key (lambda (p) (plist-get (plist-get p :task) :title)) :test #'string-prefix-p) :status))))
(let ((close (org-queue-close-compute 20260912)))
  (message "close: %s" (org-queue-close-core-summary close))
  (message "routine tomorrow: %S" (plist-get close :routine-tomorrow))
  (cl-assert (plist-get close :routine-tomorrow))
  (with-current-buffer (get-buffer-create "*smoke close*")
    (org-queue-close-mode)
    (setq org-queue--columns '(state))
    (org-queue-close--draw close)
    (message "close buffer: %d lines, first: %s" (count-lines (point-min) (point-max))
             (buffer-substring (point-min) (line-end-position)))))
(let ((log (org-queue-daylog-compute 20260912)))
  (message "day log: %d events, %d gaps" (length (plist-get log :events)) (length (plist-get log :gaps)))
  (with-current-buffer (get-buffer-create "*smoke day*")
    (org-queue-daylog-mode)
    (setq org-queue--columns '(state))
    (org-queue-daylog--draw log)
    (message "day buffer: %d lines" (count-lines (point-min) (point-max)))))
(message "routine report: %S" (org-routine-core-report (org-routine-routine) 6 0.2))
(require (quote org-capture))
(message "capture templates: %S" (mapcar #'car org-capture-templates))
(cl-assert (assoc "j" org-capture-templates))
(message "SMOKE OK")
;; wave 2
(add-to-list 'load-path (expand-file-name "source/zettapkg/org-gantt"))
(let ((pack (org-queue-review-compute 20260914)))
  (message "pack: %s" (org-queue-review-core-summary pack))
  (message "time by category: %S" (plist-get pack :time))
  (message "template rows: %S" (mapcar (lambda (r) (list (plist-get r :bucket) (plist-get r :actual) (plist-get r :expected) (plist-get r :verdict))) (plist-get pack :template)))
  (cl-assert (plist-get pack :template))
  (with-current-buffer (get-buffer-create "*smoke review*")
    (org-queue-review-mode)
    (setq org-queue--columns '(state))
    (org-queue-review--draw pack)
    (message "review buffer: %d lines" (count-lines (point-min) (point-max)))))
(message "SMOKE 2 OK")
;; wave 3: the lists over the fixture, and the module's groups
(add-to-list 'load-path (expand-file-name "source/zettapkg/org-decorate"))
(with-temp-buffer
  (insert-file-contents "modules/org/org-decorate.el")
  (eval-buffer))
(require 'org-decorate)
(let ((lists (org-decorate-lists)))
  (message "decorate lists: %d keywords, %d categories, %d targets, %d tags, %d people"
           (length (plist-get lists :keywords)) (length (plist-get lists :categories))
           (length (plist-get lists :targets)) (length (plist-get lists :tags))
           (length (plist-get lists :people)))
  (cl-assert (member "work" (plist-get lists :categories)))
  (cl-assert (cl-some (lambda (t_) (string-match-p "::\\*" t_)) (plist-get lists :targets))))
(require (quote org-super-agenda))
(message "inbox groups: %S" (mapcar (lambda (g) (plist-get g :name)) zetta-org-agenda-inbox-groups))
(cl-assert (= 5 (length zetta-org-agenda-inbox-groups)))
(message "SMOKE 3 OK")
;; wave 4: the chains over the fixture
(with-temp-buffer (insert-file-contents "modules/org/org-super-agenda.el")
  (goto-char (point-min)) (while (re-search-forward "^(use-package org-super-agenda" nil t) (replace-match "(use-package-nobrushup org-super-agenda"))
  (eval-buffer))
(add-to-list 'load-path (expand-file-name "source/zettapkg/org-chain"))
(setq org-chain-landings-file (expand-file-name "landings.el" smoke-dir)
      org-chain-applied-file (expand-file-name "applied.el" smoke-dir))
(with-temp-buffer (insert-file-contents "modules/org/org-chain.el") (eval-buffer))
(require 'org-chain)
(let ((chains (org-chain-chains)))
  (message "chains: %S" (mapcar (lambda (c) (cons (plist-get c :title) (plist-get (plist-get c :metrics) :in-flight))) chains))
  (cl-assert (= 3 (length chains))))
(message "morning line: %s" (org-chain-morning-line))
(message "close chains: %S" (mapcar (lambda (c) (and (plist-get c :prompt) t)) (org-chain-close-chains)))
(message "review lines: %S" (org-chain-review-lines 20260905 20260912))
(let ((close (org-queue-close-compute 20260912)))
  (cl-assert (plist-get (plist-get close :chains) :primed)))
(message "day groups: %S" (mapcar (lambda (g) (plist-get g :name)) zetta-org-agenda-day-groups))
(cl-assert (equal "Landed -- review" (plist-get (car zetta-org-agenda-day-groups) :name)))
(message "SMOKE 4 OK")
;; wave 5: the season, the gate, the knowledge loop over the fixture
(add-to-list 'load-path (expand-file-name "source/zettapkg/org-knowledge"))
(require 'org-queue-season)
(require 'org-queue-intake)
(require 'org-knowledge)
(setq org-queue-horizons-file (expand-file-name "todo/(todo) horizons.org" smoke-dir))
(let ((read (org-queue-season--read)))
  (message "season: theme=%S missions=%d areas=%S" (plist-get read :theme) (length (plist-get read :missions)) (plist-get read :areas))
  (cl-assert (= 3 (length (plist-get read :missions))))
  (cl-assert (equal '("emacs" 2 . 10) (car (plist-get read :areas)))))
(message "floors for the pack: %S" (org-queue-season-floors))
(let* ((tasks (org-queue-harvest))
       (served (cl-remove-if-not (lambda (task) (plist-get task :mission)) tasks)))
  (message "tasks serving a mission: %d (children inherit)" (length served))
  (cl-assert (>= (length served) 4))
  (message "orphans: %d of %d open" (length (org-queue-season-core-orphans tasks)) (length tasks)))
(with-current-buffer (find-file-noselect (expand-file-name "todo/(todo) work.org" smoke-dir))
  (goto-char (point-min))
  (re-search-forward "^\\* TODO ")
  (let ((report (org-queue-intake-report 20260919)))
    (message "intake: %s" (org-queue-intake-core-line report 20260919))
    (cl-assert (plist-get report :window))))
;; the save check refuses a fourth mission
(with-current-buffer (find-file-noselect org-queue-horizons-file)
  (goto-char (point-max))
  (insert "\n* MISSION A fourth\n:PROPERTIES:\n:SEASON: 2026-Q3\n:END:\n")
  (condition-case err (progn (save-buffer) (message "SAVE ALLOWED -- wrong"))
    (user-error (message "save refused: %s" (cadr err))))
  (revert-buffer t t t))
(let ((org-knowledge-directory (expand-file-name "wiki" smoke-dir)))
  (make-directory org-knowledge-directory t)
  (with-temp-file (expand-file-name "FavouriteProblems.org" org-knowledge-directory)
    (insert "#+title: FavouriteProblems\n* How do days add up?\n"))
  (message "problems: %S" (org-knowledge-problems))
  (delete-directory org-knowledge-directory t))
(message "SMOKE 5 OK")
;; wave 6: habits scored over the fixture, the timer predicate, the mail core
(require 'org-queue-habit)
(require 'org-queue-timer)
(require 'org-queue-mail-core)
(let ((scores (org-queue-habit-scores 20260912)))
  (message "habits: %S" (mapcar (lambda (c) (cons (plist-get (car c) :title) (plist-get (cdr c) :score))) scores))
  (cl-assert (= 5 (length scores))))
(progn
  (org-queue-habit-update 20260912 t)
  (message "habit strength written: %S" (org-entry-get (org-find-entry-with-id (plist-get (car (car (org-queue-habit-scores 20260912))) :id)) "HABIT_STRENGTH")))
(message "timer applicable at 14:00 Mon: %S; at 10:00: %S"
         (org-queue-timer-applicable-p (encode-time 0 0 14 14 9 2026))
         (org-queue-timer-applicable-p (encode-time 0 0 10 14 9 2026)))
(cl-assert (org-queue-timer-applicable-p (encode-time 0 0 14 14 9 2026)))
(cl-assert (not (org-queue-timer-applicable-p (encode-time 0 0 10 14 9 2026))))
(message "SMOKE 6 OK")
(delete-directory smoke-dir t)
(message "SMOKE ALL OK")
