name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs-version:
          - 29.4
          - 30.2

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Create stub files
        run: |
          touch ~/.dir-locals.el
          echo ";;" > ~/.private.el
          cp templates/zetta.example.el ~/.zetta.el

      - name: Run CI test
        shell: bash
        run: bin/zetta ci-test
